### ISSUE TITLE
(SUP-2737) Deprecate herd resolver

### ISSUE THREAD

**Issue by m0dular** [puppetlabs/support-tasks#87]
## Use Case
Resolving a herd by randomizing agent start times can be done using built-in tools, so we don't need this task.

## Describe the Solution You Would Like
This script should be removed and KBs should be updated to note the new method.

## Describe Alternatives You've Considered
Using the Console, `puppet job`, Bolt, or anything that can run tasks on agents:

* Set `splay` = `true` on agents
* Restart the `puppet` service so they sleep a random number of seconds before their initial run.

Using `splay` has the additional benefit of working after a restart of the machine, while the script does not.  This was important for GLIC, who restarts many agents en masse that create new herds without `splay`.

**Comment by MartyEwings** [comment]
I agree that the method of this task could use improvement, At the same time there is value in a 1 Shot "break the herd" for customers who do not use SPLAY.

Would there be benefit to reworking this as :

- Detect Splay
- Offer adding SPLAY
- Restart if SPLAY present or Splay Added
- restart with delay if not?

**Comment by jarretlavallee** [comment]
Not all customers can use `splay`. Removing this task removes one capability for the ones that cannot use `splay`.

**Comment by m0dular** [comment]
I didn't think there would be a situation where `splay` can't be used but the task could be.  Why would that be?

**Comment by jordi-garcia** [comment]
While SPLAY is a valid option to randomise the start of a Puppet agent and provides an option to resolve a herd issue, it creates a situation where a customer will need to wait an unknown random period of time for an agent to be configured based on a puppet run. This type of scenario is the one that can play against configuring an agent with SPLAY as the customer may not be willing to wait that random amount of time for an agent run. This is potentially more relevant after a server restart where the customer is waiting for a specific action that trigered the restart of the agent in the first place. As such, the need to have an adhoc approach is still valid, in my view.
As per how to do this, I feel that the view provided by a SPLAY and a one time agent restart script is a bit narrow. The execution of those options have a go a creating some randomise action which may or may not solve a herding issue. There are many variables involved these days that will need to be taking into consideration such as (primary/replica config, compilers, JRubies, number of agents, ...) in order to provide a better guarantee of solving a herding issue. As such, I am proposing to break this effort into 2 tasks, one that provides ann analysis of the environment along with available options and a second one that can execute the options that the analysis provides.
